# Configuration for the Aegis Reborn MVP
grammar_file = "grammar.bnf"
data_file = "data/BTC-USD.csv" # Example data file path

# Genetic Algorithm Parameters
population_size = 100
mutation_rate = 0.05
crossover_rate = 0.8
num_generations = 50
